# Generated by Django 3.1.3 on 2020-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_todolist1_todolist2_todolist3_todolist4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Todolist1',
        ),
        migrations.DeleteModel(
            name='Todolist2',
        ),
        migrations.DeleteModel(
            name='Todolist3',
        ),
        migrations.DeleteModel(
            name='Todolist4',
        ),
    ]
